#
# For full config options, check the docs:
#    docs.serverless.com
#

service: memes-aggregator
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    AMS3_BUCKET_NAME: ams3-bfc33e45-6504-44c4-b9be-c4113dff3763
    DMS3_BUCKET_NAME: dms3-ab6cb3dc-fbd7-49b5-b4ca-c829a9f5e5c9
    CELEBRITY_NAME: Andrzej Duda
    WEBSITES_URLS: https://kwejk.pl,https://kwejk.pl/tag/duda,https://www.facebook.com/pg/AndrzejDudaMemes/photos/,https://www.wykop.pl/tag/duda/
    SL_ALLOWED_IMG_EXTENSIONS: jpg,png
    SL_BUCKET_IMAGES_LIMIT: 100

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
      Resource: "arn:aws:s3:::*ms3*"
    - Effect: Allow
      Action:
        - rekognition:RecognizeCelebrities
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "*"

functions:
  checkCapacity:
    handler: src/handlers/check-capacity.handler

  scrapper:
    handler: src/handlers/scrapper.handler
#    events:
#      - schedule: rate(1 minute)

  saveImage:
    handler: src/handlers/save-image.handler

  recognize:
    handler: src/handlers/recognize.handler
      
  deleteImage:
    handler: src/handlers/delete-image.handler

  moveImage:
    handler: src/handlers/move-image.handler

  saveUrl:
    handler: src/handlers/save-url.handler
